# Generated by Django 3.1.5 on 2021-01-07 18:12

import apps.core.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=apps.core.models.rand_code, editable=False, max_length=20, verbose_name='Código')),
                ('task_name', models.CharField(max_length=40, verbose_name='Nome da Tarefa')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluída?')),
                ('task_status', models.CharField(blank=True, choices=[('To do', 'A Fazer'), ('doing', 'Fazendo'), ('done', 'Feito')], max_length=20, null=True, verbose_name='Status da Tarefa')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
