# Generated by Django 3.1.5 on 2021-01-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(blank=True, choices=[('todo', 'A Fazer'), ('doing', 'Fazendo'), ('done', 'Feito')], default='todo', max_length=20, null=True, verbose_name='Status da Tarefa'),
        ),
    ]
